# Generated by Django 5.1.7 on 2025-03-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=2
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
