# Generated by Django 5.1.7 on 2025-03-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of items in stock."
            ),
        ),
    ]
