# Generated by Django 5.1.7 on 2025-03-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="MEDIA_ROOT/product_images/"
            ),
        ),
    ]
